pool:
  vmImage: 'ubuntu-latest'

variables:
  # Terraform Version
  terraformVersion: '1.15.2'

  # Terraform Working Directory
  tfWorkingDir: '$(Build.SourcesDirectory)/scripts/terraform/infra-azure/environments/dev'

stages:

# =============================================================================
# TERRAFORM PLAN STAGE
# =============================================================================
- stage: Terraform_Plan
  displayName: 'Terraform Plan - Corpo Dev'

  jobs:
  - job: TerraformPlan
    displayName: 'Generate Terraform Plan for Corpo Dev'

    variables:
    - group: 'dev'

    steps:

    # -------------------------------------------------------------------------
    # Checkout Source Code
    # -------------------------------------------------------------------------
    - checkout: self
      fetchDepth: 0
      displayName: 'Checkout Source Code'

    # -------------------------------------------------------------------------
    # Install Terraform
    # -------------------------------------------------------------------------
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    # -------------------------------------------------------------------------
    # Terraform Init
    # -------------------------------------------------------------------------
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(tfWorkingDir)

    # -------------------------------------------------------------------------
    # Terraform Validate
    # -------------------------------------------------------------------------
    - task: TerraformTask@5
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(tfWorkingDir)    

    # -------------------------------------------------------------------------
    # Terraform Plan
    # -------------------------------------------------------------------------
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(tfWorkingDir)

        # Generate tfplan file

        commandOptions: '-var-file=dev.tfvars -out=$(Build.SourcesDirectory)/scripts/terraform/infra-azure/plan/corpodev-plan.tfplan'


    # -------------------------------------------------------------------------
    # Publish Terraform Plan Artifact
    # -------------------------------------------------------------------------
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Terraform Plan Artifact'
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)/scripts/terraform/infra-azure/plan/corpodev-plan.tfplan'
        artifactName: 'terraform-plan'
        publishLocation: 'Container'
    